### ISSUE TITLE
report_py3o: empty fields displayed as False

### ISSUE THREAD

**Issue by guewen** [OCA/reporting-engine#121]
Using `report_py3o` on 10.0, with a fusion server installed with Docker.
When a field is empty, the Libreoffice variable is translated to the content: `False`.
Is it something that must be changed in `report_py3o` or in `py3o.template`?
Any hint on how to resolve this issue?

**Comment by alexis-via** [comment]
It has been fixed several months ago, cf this commit:
https://bitbucket.org/faide/py3o.template/commits/bb6b837778526eb87c77ffe34b65f136411e3ab1
and with that line of code:
https://github.com/OCA/reporting-engine/blob/10.0/report_py3o/models/py3o_report.py#L244
where the escape_false=True has been added.

Are you sure you have up-to-date code for report_py3o and py3o.template ?

**Comment by alexis-via** [comment]
Maybe your docker image is not up-to-date for py3o.template... it will work fine if you have py3o.template==0.9.11.

**Comment by alexis-via** [comment]
@guewen Did you find the solution ? Can we close the bug ?

**Comment by guewen** [comment]
Thanks for your fast answer! 

You are right, this issue doesn't happen when the Local Fusion is enabled. I'm using the fusion server though. Which brings me to the next question: should we use the fusion server at all? I read it's recommended to use it but what are the reasons? Stability?

Any hint on how I could correct this issue when using the fusion server? (I had to apply #120 to be able to use the server).

Details of the versions:
<details>

```
version: '2'
services:

  oooserver:
    image: xcgd/libreoffice:latest
    volumes:
      - "data-py3o:/tmp"

  py3orenderserver:
    image: xcgd/py3oserver-docker:latest
    depends_on:
      - oooserver
    ports:
      - "8994:8994"
    volumes:
      - "data-py3o:/tmp"

  py3ofusion:
    image: xcgd/py3o.fusion:latest
    depends_on:
      - py3orenderserver
    ports:
      - "8765:8765"

  odoo:
    depends_on:
      - py3ofusion
      - py3orenderserver

volumes:
  data-py3o:
```

Libraries in py3ofusion:
```
root@2af7cdf83e86:/# pip freeze
beautifulsoup4==4.4.1
chardet==2.3.0
constantly==15.1.0
Genshi==0.7
html5lib==0.999
incremental==16.10.1
lxml==3.6.4
py3o.formats==0.3
py3o.fusion==0.8.6
py3o.renderclient==0.2
py3o.template==0.9.11
py3o.types==0.1.1
pyf.splitter==3.1
pyf.station==2.0.5
pyf.transport==2.0.1
Pygments==2.1.3
pyjon.events==1.2
pyjon.utils==0.7
python-dateutil==2.6.0
simplejson==3.10.0
six==1.10.0
Twisted==16.6.0
zope.interface==4.3.2
```

Libraries in py3orenderserver
```
root@0c667e3369dc:/# pip freeze
constantly==15.1.0
incremental==16.10.1
JPype1==0.6.1
py3o.formats==0.3
py3o.renderers.juno==0.8
py3o.renderserver==0.5.1
pyf.splitter==3.1
pyf.station==2.0.5
pyf.transport==2.0.1
pyjon.events==1.2
pyjon.utils==0.7
python-dateutil==2.6.0
simplejson==3.10.0
six==1.10.0
Twisted==16.6.0
zope.interface==4.3.2
```

</details>
